CREATE DATABASE IF NOT EXISTS rocket;

CREATE TABLE IF NOT EXISTS rocket.business (TestID INTEGER(3)
  NOT NULL AUTO_INCREMENT, Title VARCHAR(30) NOT NULL,
  About VARCHAR(1000) NOT NULL, Image MEDIUMBLOB, PRIMARY KEY(TestID));